services:
  - type: web
    name: pdftools-web  # Choose a name for your Render service
    runtime: python
    buildCommand: pip install -r requirements.txt
    startCommand: python app.py  # Or 'python app.py' for simpler testing, but gunicorn is better for production
    wsgi: true
    environmentVars:
      - key: GOOGLE_APPLICATION_CREDENTIALS_JSON  # Key to access in your app
        value: ${{secrets.GOOGLE_CREDENTIALS_JSON}}  # Reference to a Render Secret